package structs

type PlayerStatDTO struct {
	FName             string
	LName             string
	Position          string
	PlayerID          int
	Year              int
	IsRedshirt        bool
	Pancakes          int
	SacksAllowed      int
	PassAttempts      int
	PassCompletions   int
	PassYards         int
	PassTDS           int
	PassINTs          int
	LongestPass       int
	TimesSacked       int
	RushAttempts      int
	RushYards         int
	RushTDs           int
	LongestRush       int
	Fumbles           int
	Targets           int
	Catches           int
	ReceivingYards    int
	ReceivingTDs      int
	LongestCatch      int
	SoloTackles       float64
	AssistedTackles   float64
	TacklesForLoss    float64
	Sacks             float64
	ForcedFumbles     int
	RecoveredFumbles  int
	PassesDefensed    int
	INTs              int
	Safeties          int
	DefensiveTDs      int
	FGAttempts        int
	FGMade            int
	LongestFG         int
	XPAttempts        int
	XPMade            int
	KickoffTBs        int
	Punts             int
	PuntDistance      int
	LongestPunt       int
	PuntTBs           int
	PuntYards         int
	GrossPuntDistance int
	NetPuntDistance   int
	PuntInside20      int
	KickoffReturns    int
	KickReturnYards   int
	KickReturnTDs     int
	PuntReturns       int
	PuntReturnYards   int
	PuntReturnTDs     int
	STSoloTackles     float64
	STAssistedTackles float64
	PuntsBlocked      int
	FGBlocked         int
	Snaps             int
	Games             int
	GamesStarted      int
	IsInjured         bool
	InjuryType        string
	WeeksOfRecovery   uint
}

func (p *PlayerStatDTO) GetPlayerID() int {
	return p.PlayerID
}

func (p *PlayerStatDTO) MapTobasePlayerStatsObject(gameType uint8) BasePlayerStats {
	return BasePlayerStats{
		PassAttempts:         int16(p.PassAttempts),
		PassingYards:         int16(p.PassYards),
		PassCompletions:      int16(p.PassCompletions),
		PassingTDs:           int16(p.PassTDS),
		Interceptions:        int16(p.PassINTs),
		LongestPass:          int16(p.LongestPass),
		Sacks:                int16(p.TimesSacked),
		RushAttempts:         int16(p.RushAttempts),
		RushingYards:         int16(p.RushYards),
		RushingTDs:           int16(p.RushTDs),
		LongestRush:          int16(p.LongestRush),
		Fumbles:              int16(p.Fumbles),
		Targets:              int16(p.Targets),
		Catches:              int16(p.Catches),
		ReceivingYards:       int16(p.ReceivingYards),
		ReceivingTDs:         int16(p.ReceivingTDs),
		LongestReception:     int16(p.LongestCatch),
		Pancakes:             int16(p.Pancakes),
		SacksAllowed:         int16(p.SacksAllowed),
		SoloTackles:          p.SoloTackles,
		AssistedTackles:      p.AssistedTackles,
		TacklesForLoss:       p.TacklesForLoss,
		SacksMade:            p.Sacks,
		ForcedFumbles:        int16(p.ForcedFumbles),
		RecoveredFumbles:     int16(p.RecoveredFumbles),
		Safeties:             int16(p.Safeties),
		DefensiveTDs:         int16(p.DefensiveTDs),
		PassDeflections:      int16(p.PassesDefensed),
		InterceptionsCaught:  int16(p.INTs),
		LongestFG:            int16(p.LongestFG),
		FGAttempts:           int16(p.FGAttempts),
		FGMade:               int16(p.FGMade),
		ExtraPointsAttempted: int16(p.XPAttempts),
		ExtraPointsMade:      int16(p.XPMade),
		KickoffTouchbacks:    int16(p.KickoffTBs),
		Punts:                int16(p.Punts),
		PuntTouchbacks:       int16(p.PuntTBs),
		PuntsInside20:        int16(p.PuntInside20),
		KickReturns:          int16(p.KickoffReturns),
		KickReturnTDs:        int16(p.KickReturnTDs),
		KickReturnYards:      int16(p.KickReturnYards),
		PuntReturns:          int16(p.PuntReturns),
		PuntReturnYards:      int16(p.PuntReturnYards),
		PuntReturnTDs:        int16(p.PuntReturnTDs),
		STSoloTackles:        p.STSoloTackles,
		STAssistedTackles:    p.STAssistedTackles,
		PuntsBlocked:         int16(p.PuntsBlocked),
		FGBlocked:            int16(p.FGBlocked),
		Snaps:                int16(p.Snaps),
		PlayedGame:           int16(p.Games),
		StartedGame:          int16(p.GamesStarted),
		WasInjured:           p.IsInjured,
		InjuryType:           p.InjuryType,
		WeeksOfRecovery:      p.WeeksOfRecovery,
		GameType:             gameType,
	}
}
