name: CI/CD Pipeline to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'

    - name: Build and test
      run: |
        go build -v ./...

    - name: Log in to Docker Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login myregistry.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t myregistry.azurecr.io/myapp:${{ github.sha }} .

    - name: Push Docker Image
      run: docker push myregistry.azurecr.io/myapp:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyWebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'myregistry.azurecr.io/myapp:${{ github.sha }}'
