name: CI/CD Pipeline to Azure Web App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DB: ${{secrets.DB}}
      CS: ${{secrets.CS}}
      SFAKEY: ${{secrets.SFAKEY}}
      SFAUSER: ${{secrets.SFA}}
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
      VITE_SIMFBA_KEY: ${{ secrets.VITE_SIMFBA_KEY }}
      VITE_SIMFBA_USER: ${{ secrets.VITE_SIMFBA_USER }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.20"

      - name: Build
        run: |
          go build -v ./...

      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_P }} | docker login simfba.azurecr.io --username ${{ secrets.DOCKER_U }} --password-stdin

      - name: Build Docker Image
        run: docker build -t simfba.azurecr.io/simfba:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push simfba.azurecr.io/simfba:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "simfba"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "simfba.azurecr.io/simfba:${{ github.sha }}"
